### ISSUE TITLE
Does it work with Notification Service Extensions & Notification Content Extensions?

### ISSUE THREAD

**Issue by mxcl** [acoomans/SimulatorRemoteNotifications#17]

**Comment by gbero** [comment]
I'd be curious to know as well but I doubt it would work.

**Comment by marius-serban** [comment]
It doesn't work with Notification Service Extensions & Notification Content Extensions. It is just an extension on `UIApplication` that runs a UDP socket server and calls the the `didReceiveRemoteNotification` delegate methods.
