### ISSUE TITLE
Error with Code = 3840

### ISSUE THREAD

**Issue by DevAlloy** [acoomans/SimulatorRemoteNotifications#2]
I send two JSON's:
<code>echo -n '{"aps":{"alert" : "message","badge" : 99,"sound" : "default"},"storeId" : **5475878**}' | nc -4u -w1 localhost 9930
</code>

<code>echo -n '{"aps":{"alert" : "message","badge" : 99,"sound" : "default"},"storeId" : **54758**}' | nc -4u -w1 localhost 9930
</code>

Difference only in storeId. First works fine, but second causes error:
**SimulatorRemoteNotification: error = Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (Garbage at end.) UserInfo=0xb23dc90 {NSDebugDescription=Garbage at end.}**

I tried to resolve this issue but failed:
When we take string from buffer in second case string looks like this:
<code>{"aps":{"alert" : "message","badge" : 99,"sound" : "default"},"storeId" : 54758 **}}** </code>

Two braces instead of one in first case.

I don't understand how could it be.

**Comment by MVakas** [comment]
Struggling with same issue.
